In [1]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd


In [2]:
#Series takes sequence form data
obj = Series(np.random.randint(-10,10,5))
obj

0    2
1   -9
2    0
3    3
4   -1
dtype: int64

In [3]:
obj.values

array([ 2, -9,  0,  3, -1])

In [4]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
obj2 = Series(obj.values, index = ['d','b','a','c','e'])
obj2

d    2
b   -9
a    0
c    3
e   -1
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c', 'e'], dtype='object')

In [7]:
print (obj2['a'])

0


In [8]:
obj2['d'] = 6
print (obj2)

d    6
b   -9
a    0
c    3
e   -1
dtype: int64


In [9]:
# Indexing use list form. [,,,]
obj2[['c','a','d']]

c    3
a    0
d    6
dtype: int64

In [10]:
obj2[obj2>0]

d    6
c    3
dtype: int64

In [11]:
np.exp(obj2)

d    403.428793
b      0.000123
a      1.000000
c     20.085537
e      0.367879
dtype: float64

In [12]:
obj2*2

d    12
b   -18
a     0
c     6
e    -2
dtype: int64

In [13]:
'b' in obj2

True

In [14]:
'f' in obj2

False

In [17]:
sdata = dict(zip(['Ohio','Texas','Oregon','Utah'], np.random.randint(10000,40000,4)))
sdata

{'Ohio': 28841, 'Oregon': 20660, 'Texas': 39179, 'Utah': 23403}

In [19]:
obj3 = Series(sdata)
obj3

Ohio      28841
Oregon    20660
Texas     39179
Utah      23403
dtype: int64

In [21]:
# if key of dict and index is both specified, AND , operation filter each element. with index element can
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index = states) # index work as mask if key of input data.exist
obj4

California        NaN
Ohio          28841.0
Oregon        20660.0
Texas         39179.0
dtype: float64

In [25]:
obj4_5 = Series(list(sdata.values()), index = states)
obj4_5

California    28841
Ohio          39179
Oregon        20660
Texas         23403
dtype: int64

In [26]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [29]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
obj3

Ohio      28841
Oregon    20660
Texas     39179
Utah      23403
dtype: int64

In [31]:
obj4

California        NaN
Ohio          28841.0
Oregon        20660.0
Texas         39179.0
dtype: float64

In [32]:
obj3 + obj4

California        NaN
Ohio          57682.0
Oregon        41320.0
Texas         78358.0
Utah              NaN
dtype: float64

In [35]:
obj4.name = 'population'
obj4.index.name = 'state'

In [36]:
obj4

state
California        NaN
Ohio          28841.0
Oregon        20660.0
Texas         39179.0
Name: population, dtype: float64

In [38]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan', 'Joe']
obj

Bob      6
Steve   -9
Jeff     0
Ryan     3
Joe     -1
dtype: int64

In [39]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year' : [2000,2001,2002,2001,2002],
       'pop' : [1.5, 1.7, 3.6, 2.4, 2.9] }
frame = DataFrame(data)
frame
#For Series, Key is index name/ Value is along columndir
#DataFrame, key is the column name, / value(columns) is along row dir

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [41]:
DataFrame(data, columns = ['year', 'state', 'pop']) # Filter & Ordering

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [42]:
DataFrame(data, columns = ['state','year','pop']) #Specify Ordering

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [43]:
DataFrame(data, columns = ['state', 'year'])

state  year
0    Ohio  2000
1    Ohio  2001
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002

In [44]:
DataFrame(data, columns = ['state', 'age']) # Non-existing values in to NaN

state  age
0    Ohio  NaN
1    Ohio  NaN
2    Ohio  NaN
3  Nevada  NaN
4  Nevada  NaN

In [45]:
#Series and DataFrame both take dict and list types, but key values are treated differently
# for Series key is index names (with value corresponding series element)

# for DataFrame key is column names (with value(listform) corresponding column)

In [48]:
#length of index should be same as the length of the input data columns
frame2 = DataFrame(data, columns = ['year', 'state', 'pop','debt'], index=['one', 'two', 'three', 'four', 'five'])

frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [50]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [51]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [52]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [53]:
frame2.ix['three']


/home/june/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [55]:
#by row, indexing (time)
#name
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [58]:
#number
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [59]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [60]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [63]:
val = Series([-1.2, -1.5, -1.7], index = ['two','four','five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [79]:
#columnwise assigning : same size sequence/ dict
#columnwise assigning : series with defined indexing
frame2['debt'] = [1,2,3,4,5]
frame2

year   state  pop  debt
one    2000    Ohio  1.5     1
two    2001    Ohio  1.7     2
three  2002    Ohio  3.6     3
four   2001  Nevada  2.4     4
five   2002  Nevada  2.9     5

In [80]:
#Complelte Reassigning.
frame2['debt'] = Series([1,2,3], index=['two', 'four', 'one'])
frame2

year   state  pop  debt
one    2000    Ohio  1.5   3.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   2.0
five   2002  Nevada  2.9   NaN

In [81]:
frame2['debt'] = Series([1], index = ['one'])
frame2

year   state  pop  debt
one    2000    Ohio  1.5   1.0
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9   NaN

In [83]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   1.0     True
two    2001    Ohio  1.7   NaN     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9   NaN    False

In [85]:
frame2.state == 'Ohio'

one       True
two       True
three     True
four     False
five     False
Name: state, dtype: bool

In [ ]:
del frame2['eastern']

In [109]:
frame2.index
frame2.columns.name.clear
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object', name=['year2', 'state2', 'pop2', 'debt2'])

In [100]:
obj.index
obj4.name = 'population'
obj4.index.name = 'state'
#obj4.index = [...]

Index(['Bob', 'Steve', 'Jeff', 'Ryan', 'Joe'], dtype='object')

In [110]:
frame2['debt'] = np.arange(5.)
frame2

['year2', 'state2', 'pop2', 'debt2']  year   state  pop  debt
one                                   2000    Ohio  1.5   0.0
two                                   2001    Ohio  1.7   1.0
three                                 2002    Ohio  3.6   2.0
four                                  2001  Nevada  2.4   3.0
five                                  2002  Nevada  2.9   4.0

In [111]:
val = Series([-1.2, -1.5, -1.7],index = ['two', 'four','five'])
frame2['debt'] = val
frame2

['year2', 'state2', 'pop2', 'debt2']  year   state  pop  debt
one                                   2000    Ohio  1.5   NaN
two                                   2001    Ohio  1.7  -1.2
three                                 2002    Ohio  3.6   NaN
four                                  2001  Nevada  2.4  -1.5
five                                  2002  Nevada  2.9  -1.7

In [113]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

['year2', 'state2', 'pop2', 'debt2']  year   state  pop  debt  eastern
one                                   2000    Ohio  1.5   NaN     True
two                                   2001    Ohio  1.7  -1.2     True
three                                 2002    Ohio  3.6   NaN     True
four                                  2001  Nevada  2.4  -1.5    False
five                                  2002  Nevada  2.9  -1.7    False

In [117]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object', name=['year2', 'state2', 'pop2', 'debt2'])

In [122]:
frame2.columns.names.clear()
frame2.columns.name.clear()
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object', name=[])

In [125]:
#Strict definition with dict(Series) in a dict(DataFrame)
# { columnname1 : Series1, columnname2 : Series2, columnname3 : Series3...}
# where Series# === { idx1 : val1, idx2 : val2, idx3 : val3}
pop = {'Nevada' : {2001: 2.4, 2002: 2.9},
      'Ohio' : {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [126]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [127]:
DataFrame(pop, index =range(2001,2004))

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [129]:
# assign series type object
pdata = {'Ohio' : frame3['Ohio'][:-1], 'Nevada' : frame3['Nevada'][:2]}
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [131]:
#Naming rows and columns
frame3.index.name = 'year' ; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [132]:
#return ndarray(Numpy)
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [133]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [139]:
#2d nd array
DataFrame(np.random.randn(3,3))
#dict of arrays, lists, or tuples.
DataFrame({'fruits':[1,2,3,4],'a':[1,2,3,4]}, index=['spring','summer','fall','winter'])
#list of dicts or Series
#dict of Series
#Numpy structured / record array
#dict of dicts
#List of lists or tuples
DataFrame([range(5), map(lambda x: x+5, range(5))]), #rowwise insert

#Another DataFrame

#NumPy Masked Array

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

In [141]:
#index object
obj = Series(range(3), index = ['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [142]:
obj.index[1:]

Index(['b', 'c'], dtype='object')

In [148]:
#index object is immutable
obj.index[1] = 'd'

TypeError: Index does not support mutable operations

In [ ]:
pdindex = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index = pdindex)
obj2_5 = Series([1.5,-2.4,0], index = np.arange(3))
obj2_7 = Series([1.5, -2.4, 0], index = [0,1,2])
#index object type
#Index
#Int64Index
#MultiIndex
#DatetimeIndex
#PeriodIndex

In [159]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [158]:
'Ohio' in frame3.index

False

In [160]:
'Ohio' in frame3.columns

True

In [173]:
f3idx = frame3.index
f3idx.append(f3idx)


Int64Index([2000, 2001, 2002, 2000, 2001, 2002], dtype='int64', name='year')

In [175]:
f3idx.intersection(f3idx)

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

In [176]:
f3idx.union(f3idx)

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

In [179]:
f3idx.isin([2000, 2001])

array([ True,  True, False], dtype=bool)

In [180]:
f3idx.delete(0)

Int64Index([2001, 2002], dtype='int64', name='year')

In [181]:
f3idx.drop(2001)

Int64Index([2000, 2002], dtype='int64', name='year')

In [182]:
f3idx.insert(1,2)

Int64Index([2000, 2, 2001, 2002], dtype='int64', name='year')

In [183]:
f3idx.is_monotonic #increasing monotonically?

True

In [184]:
f3idx.is_unique

True

In [186]:
f3idx.unique()

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

In [192]:
#Reindexing
obj = Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b','a', 'c'])
obj

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [193]:
obj2 = obj.reindex(['a', 'b', 'c', 'd','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [194]:
obj.reindex(['a','b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [195]:
obj3 = Series(['blue', 'purple', 'yellow'], index = [0,2,4])

In [200]:
obj3.reindex(range(6))

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [204]:
obj3.reindex(range(6), method = 'ffill') #Forward fill #fill empty with previous values
obj3.reindex(range(6), method = 'pad')


0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [205]:
obj3.reindex(range(6), method = 'bfill')
obj3.reindex(range(6), method = 'backfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [212]:
frame = DataFrame(np.arange(9).reshape((3,3)), index = ['a', 'c','d'],
                  columns = ['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [213]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [210]:
states = ['Texas', 'Utah', 'California']
#One list refer to Row/Column
# [[],[]] : list of row, list of column
# [ (),()] rows,columns

# [[,]] : list of rows(create if not ex)  || DIFFER || [(,)] : coordinate (row,column)

#
frame.ix[['a','b','c','d'],states]

/home/june/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [220]:

frame.loc[['a','b','c','d'],states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [234]:
frame.loc[['a'], ['Texas']]

Texas
a      1

In [235]:
frame.loc[['a','Texas']]

Ohio  Texas  California
a       0.0    1.0         2.0
Texas   NaN    NaN         NaN

In [231]:
frame.loc[('a', 'Texas')]

1

In [237]:
frame.loc[('a', 'b'),('Texas', 'California')]

Texas  California
a    1.0         2.0
b    NaN         NaN

In [238]:
frame.loc[['a', 'b'], ['Texas', 'California']]

Texas  California
a    1.0         2.0
b    NaN         NaN

In [245]:
frame.loc[['a','b'],['Texas','California']]
frame.loc[['a','Texas']]

Ohio  Texas  California
a       0.0    1.0         2.0
Texas   NaN    NaN         NaN

In [248]:
frame.loc[('a','Texas')] # => 1

1

In [249]:
frame.loc[('a','Texas'), ('b','California')] # table with assignment

b  California
a     NaN         2.0
Texas NaN         NaN

In [263]:
frame.iloc[:,:]

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [273]:
frame.loc[('c', 'd'),:]

Ohio  Texas  California
c     3      4           5
d     6      7           8

In [282]:
#Columnwise Selection
frame.Texas[:2]
frame['Texas'][:2]


a    1
c    4
Name: Texas, dtype: int64

In [283]:
obj = Series(np.arange(5.), index = ['a', 'b', 'c','d', 'e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64